apiVersion: v1
kind: Namespace
metadata:
  name: asmblyr-collaborative-dev
  labels:
    app.kubernetes.io/part-of: asmblyr-collaborative
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-files
  namespace: asmblyr-collaborative-dev
automountServiceAccountToken: false
