import type { SchemaField } from "@asmblyr-collaborative/contracts";
import { parseSchemaSnapshot } from "./validation.js";
import { generateRuntimeSchema } from "./runtime.js";
import { generatePluginTypes } from "./plugin-types.js";

function valueType(field: SchemaField, write: boolean): string {
  let type = field.enum?.map((value) => JSON.stringify(value)).join(" | ");
  if (type && field.type === "strings") {
    type = `(${type})[]`;
  }
  if (!type) {
    type = {
      string: "string",
      number: "number",
      boolean: "boolean",
      json: "JsonValue",
      strings: "string[]",
    }[field.type];
  }
  // Core accepts string IDs for integer foreign keys as well as integers.
  if (write && field.relationKey === "serial") {
    type = "number | string";
  }
  return field.nullable ? `${type} | null` : type;
}
/** Standard TypeScript source; no transforms or consumer build plugins. */
export function generateSchemaTypes(input: unknown): string {
  const snapshot = parseSchemaSnapshot(input);
  const imports = [];
  if (snapshot.collections.length) {
    imports.push("CollectionSchema");
  }
  if (
    snapshot.collections.some((collection) =>
      collection.fields.some(
        (field) =>
          field.type === "json" &&
          (["read", "create", "update"] as const).some(
            (action) => collection.actions[action] && field[action],
          ),
      ),
    )
  ) {
    imports.push("JsonValue");
  }
  const lines = [
    "// Generated by asm schema pull. Do not edit.",
    `// Schema version: 1; hash: ${snapshot.hash}`,
    'import { defineSchema } from "@asmblyr-collaborative/sdk";',
    ...(imports.length
      ? [
          `import type { ${imports.join(", ")} } from "@asmblyr-collaborative/sdk";`,
        ]
      : []),
    "",
  ];
  for (const action of ["read", "create", "update"] as const) {
    const title = action[0].toUpperCase() + action.slice(1);
    lines.push(`export interface ${title} {`);
    for (const collection of snapshot.collections) {
      if (!collection.actions[action]) {
        lines.push(`  ${JSON.stringify(collection.name)}: never;`);
        continue;
      }
      lines.push(`  ${JSON.stringify(collection.name)}: {`);
      for (const field of collection.fields.filter((field) => field[action])) {
        const optional =
          action === "update" ||
          (action === "create" && !field.requiredOnCreate);
        lines.push(
          `    ${JSON.stringify(field.name)}${optional ? "?" : ""}: ${valueType(field, action !== "read")};`,
        );
      }
      lines.push("  };");
    }
    lines.push("}", "");
  }
  lines.push("export interface Schema {");
  for (const collection of snapshot.collections) {
    const key = JSON.stringify(collection.name);
    lines.push(
      `  ${key}: CollectionSchema<Read[${key}], Create[${key}], Update[${key}], ${collection.actions.delete}>;`,
    );
  }
  lines.push(
    "}",
    "",
    `export const schemaHash = ${JSON.stringify(snapshot.hash)} as const;`,
    "",
    ...generatePluginTypes(snapshot.methods),
    ...generateRuntimeSchema(snapshot),
  );
  return lines.join("\n");
}
