{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "collaborative.name" . }}
  labels:
    {{- include "collaborative.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- $host := (urlParse (required "publicUrl is required" .Values.publicUrl)).hostname }}
  {{- with .Values.ingress.tlsSecretName }}
  tls:
    - hosts: [{{ $host | quote }}]
      secretName: {{ . | quote }}
  {{- end }}
  rules:
    - host: {{ $host | quote }}
      http:
        paths:
          {{- range $path := list "/api" "/oauth" "/sign/sso" "/connections/google/callback" }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "collaborative.name" $ }}-core
                port: { number: 3001 }
          {{- end }}
          {{- range $path := list "/oauth/interaction" "/" }}
          - path: {{ $path }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "collaborative.name" $ }}-ui
                port: { number: 3000 }
          {{- end }}
{{- end }}
